using System;
using System.Collections.Generic;
using System.Text;

namespace Examples.PaymentGateway.Domain
{
    public class BankPaymentResponse
    {
        /// <summary>
        /// An identifier generated by the bank for the transaction.
        /// </summary>
        /// <remarks>
        /// Assumption: Different banks have different Id systems and
        /// the identifier will need to be flexible i.e. string type.
        /// If a payment is declined then an id is still provided.
        /// </remarks>
        public string BankPaymentId { get; set; }

        public PaymentStatus Result { get; set; }
    }
}
